server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:1080}
spring:
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:1081}/${DB_NAME:mockserver}
    username: ${DB_USER:mockserver}
    password: ${DB_PASS:mockserver}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:1081}/${DB_NAME:mockserver}
    user: ${DBMIGRATION_USER:mockserver}
    password: ${DBMIGRATION_PASS:mockserver}
    schemas:
      - 'public'
    locations:
      - 'classpath:db/migration'
    sqlMigrationPrefix: 'V'
    out-of-order: true
    placeholders:
      application_user: ${DB_USER:mockserver}

logging:
  level:
    com: ${LOGGING:info}